### ISSUE TITLE
Add getElementContaining(const Element*)

### ISSUE THREAD

**Issue by akva2** [VikingScientist/LRsplines#18]
In user code dealing with mixed finite elements you often see constructs like

```
int elem = surface->getElementContaining((elem2->umin()+elem2->umax())/2.0, ...).
```

it would be great to see
```
  int elem = surface->getElementContaining(elem2);
```

in particular it could be used to work with 'LRSpline' objects rather than LRSplineSurface|Volum, making it possible to unify some code.

**Comment by VikingScientist** [comment]
The problem happens when `elem2` covers multiple other elements, which makes us have to return a vector of `int`'s . A proposed solution is explicitly calling the element midpoint, so the code would look like this:
``` c++
int elem = surface->getElementContaining(elem2->midpoint())
```
This is then supported in both Surface, Volume and their parent class.
