### ISSUE TITLE
Append mode for postscript output

### ISSUE THREAD

**Issue by kmokstad** [VikingScientist/LRsplines#29]
For a multi-patch model you can now only get a single eps-file for each patch.
It would be better to store all patches in the same file to display the assembled model.
You essentially only need to concatenate the files for each patch while changing the %%BoundingBox statement. One could do this manually, except there appears to be some automatic scaling of each patch that makes it difficult, unless all patches have the same size.

Therefore, an append mode would be better, where the bounding box is set by the caller, and each patch is appended to the provided file, if it already exists.

This makes sense only for the physical mesh, of course (and without the dots).

**Comment by VikingScientist** [comment]
This has already been implemented. See https://github.com/VikingScientist/LRsplines/blob/master/Apps/drawLRmultipatch.cpp which takes as input one or more `.lr` files where each file is a single patch and together they form a multipatch model. The executable then combines these into a single postscript output file. If you have the patches as separate files, then the quickest solution would just be to use this application directly, but the functionality could probably have more integrated support in IFEM by borrowing the same logic as you find there.

**Comment by kmokstad** [comment]
Yes, this utility works fine. Actually, it also works having all patches is in the same lr-file.
Made a few improvements though, see #30
