### ISSUE TITLE
Compilation error in TensorComparison app. 

### ISSUE THREAD

**Issue by norouzzadeh** [VikingScientist/LRsplines#4]
On Ubuntu 12.10, i get the following compilation error:
LRsplines/LRsplines-master/Apps/TensorComparison.cpp: In function ‘int main(int, char**)’:
LRsplines/LRsplines-master/Apps/TensorComparison.cpp:118:28: error: no matching function for call to ‘LR::LRSplineSurface::point(std::vector<Go::Point>&, double&, double&, int)’

Disabling this, the packaged compiled successfully.

**Comment by VikingScientist** [comment]
Could not reproduce.

It would seem that this is an issue when trying to compile apps which depend on the GoTools library, but this is not available. Do you have Boost and/or GoTools installed on your system?
